name: Build docs

on:
  push:
    paths:
      - 'docs/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Deploy docs
        uses: shalzz/zola-deploy-action@v0.13.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          BUILD_DIR: docs/
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
